// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllVideosWithUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllVideosWithUserIDRequest) Reset() {
	*x = GetAllVideosWithUserIDRequest{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllVideosWithUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVideosWithUserIDRequest) ProtoMessage() {}

func (x *GetAllVideosWithUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVideosWithUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllVideosWithUserIDRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllVideosWithUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type VideoMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vid              string                 `protobuf:"bytes,1,opt,name=vid,proto3" json:"vid,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	MimeType         string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSizeBytes    int64                  `protobuf:"varint,4,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"` // better as number
	Url              string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	UploadDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=upload_date,json=uploadDate,proto3" json:"upload_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VideoMetadata) Reset() {
	*x = VideoMetadata{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadata) ProtoMessage() {}

func (x *VideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadata.ProtoReflect.Descriptor instead.
func (*VideoMetadata) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *VideoMetadata) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *VideoMetadata) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *VideoMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *VideoMetadata) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *VideoMetadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoMetadata) GetUploadDate() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadDate
	}
	return nil
}

type GetAllVideosWithUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoMetadata       `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllVideosWithUserIDResponse) Reset() {
	*x = GetAllVideosWithUserIDResponse{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllVideosWithUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVideosWithUserIDResponse) ProtoMessage() {}

func (x *GetAllVideosWithUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVideosWithUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllVideosWithUserIDResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllVideosWithUserIDResponse) GetVideos() []*VideoMetadata {
	if x != nil {
		return x.Videos
	}
	return nil
}

type DeleteVideoFromThirdPartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           string                 `protobuf:"bytes,1,opt,name=vid,proto3" json:"vid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoFromThirdPartyRequest) Reset() {
	*x = DeleteVideoFromThirdPartyRequest{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoFromThirdPartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoFromThirdPartyRequest) ProtoMessage() {}

func (x *DeleteVideoFromThirdPartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoFromThirdPartyRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoFromThirdPartyRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteVideoFromThirdPartyRequest) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *DeleteVideoFromThirdPartyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteVideoFromThirdPartyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoFromThirdPartyResponse) Reset() {
	*x = DeleteVideoFromThirdPartyResponse{}
	mi := &file_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoFromThirdPartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoFromThirdPartyResponse) ProtoMessage() {}

func (x *DeleteVideoFromThirdPartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoFromThirdPartyResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoFromThirdPartyResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVideoFromThirdPartyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVideoFromThirdPartyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Upload video from third site
type UploadVideoFromThirdPartyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsLastChunk      bool                   `protobuf:"varint,1,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChunkData        []byte                 `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	FileSize         int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,5,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	MimeType         string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadVideoFromThirdPartyRequest) Reset() {
	*x = UploadVideoFromThirdPartyRequest{}
	mi := &file_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoFromThirdPartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoFromThirdPartyRequest) ProtoMessage() {}

func (x *UploadVideoFromThirdPartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoFromThirdPartyRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoFromThirdPartyRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{5}
}

func (x *UploadVideoFromThirdPartyRequest) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *UploadVideoFromThirdPartyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadVideoFromThirdPartyRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *UploadVideoFromThirdPartyRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadVideoFromThirdPartyRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *UploadVideoFromThirdPartyRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type UploadVideoFromThirdPartyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoFromThirdPartyResponse) Reset() {
	*x = UploadVideoFromThirdPartyResponse{}
	mi := &file_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoFromThirdPartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoFromThirdPartyResponse) ProtoMessage() {}

func (x *UploadVideoFromThirdPartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoFromThirdPartyResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoFromThirdPartyResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{6}
}

func (x *UploadVideoFromThirdPartyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadVideoFromThirdPartyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UploadVideoFromThirdPartyResponse) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Vid           string                 `protobuf:"bytes,2,opt,name=vid,proto3" json:"vid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVideoRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeleteVideoRequest) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           string                 `protobuf:"bytes,1,opt,name=vid,proto3" json:"vid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{9}
}

func (x *GetVideoRequest) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

type GetVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	IsLastChunk   bool                   `protobuf:"varint,3,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResponse) Reset() {
	*x = GetVideoResponse{}
	mi := &file_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResponse) ProtoMessage() {}

func (x *GetVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{10}
}

func (x *GetVideoResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *GetVideoResponse) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *GetVideoResponse) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

type UploadVideoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	MimeType         string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ChunkData        []byte                 `protobuf:"bytes,4,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`          // Partial video data
	ChunkNumber      int32                  `protobuf:"varint,5,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`   // Optional: track chunk order
	IsLastChunk      bool                   `protobuf:"varint,6,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"` // Optional: signal last chunk
	FileSize         int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`            // Total file size in bytes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{11}
}

func (x *UploadVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadVideoRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *UploadVideoRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadVideoRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *UploadVideoRequest) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *UploadVideoRequest) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *UploadVideoRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{12}
}

func (x *UploadVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadVideoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UploadVideoResponse) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\x05video\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x1dGetAllVideosWithUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe2\x01\n" +
	"\rVideoMetadata\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\tR\x03vid\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12&\n" +
	"\x0ffile_size_bytes\x18\x04 \x01(\x03R\rfileSizeBytes\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12;\n" +
	"\vupload_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadDate\"N\n" +
	"\x1eGetAllVideosWithUserIDResponse\x12,\n" +
	"\x06videos\x18\x01 \x03(\v2\x14.video.VideoMetadataR\x06videos\"L\n" +
	" DeleteVideoFromThirdPartyRequest\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\tR\x03vid\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"W\n" +
	"!DeleteVideoFromThirdPartyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe5\x01\n" +
	" UploadVideoFromThirdPartyRequest\x12\"\n" +
	"\ris_last_chunk\x18\x01 \x01(\bR\visLastChunk\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fR\tchunkData\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12+\n" +
	"\x11original_filename\x18\x05 \x01(\tR\x10originalFilename\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\"\x7f\n" +
	"!UploadVideoFromThirdPartyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\">\n" +
	"\x12DeleteVideoRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x10\n" +
	"\x03vid\x18\x02 \x01(\tR\x03vid\"I\n" +
	"\x13DeleteVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\x0fGetVideoRequest\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\tR\x03vid\"x\n" +
	"\x10GetVideoResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12\"\n" +
	"\ris_last_chunk\x18\x03 \x01(\bR\visLastChunk\"\xfa\x01\n" +
	"\x12UploadVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x04 \x01(\fR\tchunkData\x12!\n" +
	"\fchunk_number\x18\x05 \x01(\x05R\vchunkNumber\x12\"\n" +
	"\ris_last_chunk\x18\x06 \x01(\bR\visLastChunk\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\"q\n" +
	"\x13UploadVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl2\xa4\x04\n" +
	"\fVideoService\x12e\n" +
	"\x16GetAllVideosWithUserID\x12$.video.GetAllVideosWithUserIDRequest\x1a%.video.GetAllVideosWithUserIDResponse\x12F\n" +
	"\vUploadVideo\x12\x19.video.UploadVideoRequest\x1a\x1a.video.UploadVideoResponse(\x01\x12=\n" +
	"\bGetVideo\x12\x16.video.GetVideoRequest\x1a\x17.video.GetVideoResponse0\x01\x12D\n" +
	"\vDeleteVideo\x12\x19.video.DeleteVideoRequest\x1a\x1a.video.DeleteVideoResponse\x12p\n" +
	"\x19UploadVideoFromThirdParty\x12'.video.UploadVideoFromThirdPartyRequest\x1a(.video.UploadVideoFromThirdPartyResponse(\x01\x12n\n" +
	"\x19DeleteVideoFromThirdParty\x12'.video.DeleteVideoFromThirdPartyRequest\x1a(.video.DeleteVideoFromThirdPartyResponseB\tZ\a.;videob\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_video_proto_goTypes = []any{
	(*GetAllVideosWithUserIDRequest)(nil),     // 0: video.GetAllVideosWithUserIDRequest
	(*VideoMetadata)(nil),                     // 1: video.VideoMetadata
	(*GetAllVideosWithUserIDResponse)(nil),    // 2: video.GetAllVideosWithUserIDResponse
	(*DeleteVideoFromThirdPartyRequest)(nil),  // 3: video.DeleteVideoFromThirdPartyRequest
	(*DeleteVideoFromThirdPartyResponse)(nil), // 4: video.DeleteVideoFromThirdPartyResponse
	(*UploadVideoFromThirdPartyRequest)(nil),  // 5: video.UploadVideoFromThirdPartyRequest
	(*UploadVideoFromThirdPartyResponse)(nil), // 6: video.UploadVideoFromThirdPartyResponse
	(*DeleteVideoRequest)(nil),                // 7: video.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),               // 8: video.DeleteVideoResponse
	(*GetVideoRequest)(nil),                   // 9: video.GetVideoRequest
	(*GetVideoResponse)(nil),                  // 10: video.GetVideoResponse
	(*UploadVideoRequest)(nil),                // 11: video.UploadVideoRequest
	(*UploadVideoResponse)(nil),               // 12: video.UploadVideoResponse
	(*timestamppb.Timestamp)(nil),             // 13: google.protobuf.Timestamp
}
var file_video_proto_depIdxs = []int32{
	13, // 0: video.VideoMetadata.upload_date:type_name -> google.protobuf.Timestamp
	1,  // 1: video.GetAllVideosWithUserIDResponse.videos:type_name -> video.VideoMetadata
	0,  // 2: video.VideoService.GetAllVideosWithUserID:input_type -> video.GetAllVideosWithUserIDRequest
	11, // 3: video.VideoService.UploadVideo:input_type -> video.UploadVideoRequest
	9,  // 4: video.VideoService.GetVideo:input_type -> video.GetVideoRequest
	7,  // 5: video.VideoService.DeleteVideo:input_type -> video.DeleteVideoRequest
	5,  // 6: video.VideoService.UploadVideoFromThirdParty:input_type -> video.UploadVideoFromThirdPartyRequest
	3,  // 7: video.VideoService.DeleteVideoFromThirdParty:input_type -> video.DeleteVideoFromThirdPartyRequest
	2,  // 8: video.VideoService.GetAllVideosWithUserID:output_type -> video.GetAllVideosWithUserIDResponse
	12, // 9: video.VideoService.UploadVideo:output_type -> video.UploadVideoResponse
	10, // 10: video.VideoService.GetVideo:output_type -> video.GetVideoResponse
	8,  // 11: video.VideoService.DeleteVideo:output_type -> video.DeleteVideoResponse
	6,  // 12: video.VideoService.UploadVideoFromThirdParty:output_type -> video.UploadVideoFromThirdPartyResponse
	4,  // 13: video.VideoService.DeleteVideoFromThirdParty:output_type -> video.DeleteVideoFromThirdPartyResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
